jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        SF\CapBundle\Entity\CapUser: plaintext
     #       algorithm:        sha1
      #      encode_as_base64: false
       #     iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        main:
            entity: { class: SFCapBundle:CapUser, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:    ^/login$
            provider: main
            anonymous: ~
        secured_area:
            provider: main
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }