<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121111210707 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE CapGoalSubscription (id INT AUTO_INCREMENT NOT NULL, runner_id INT DEFAULT NULL, goal_id INT DEFAULT NULL, date DATE NOT NULL, INDEX IDX_D8F3EF633C7FB593 (runner_id), INDEX IDX_D8F3EF63667D1AFE (goal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE CapGoalSubscription ADD CONSTRAINT FK_D8F3EF633C7FB593 FOREIGN KEY (runner_id) REFERENCES CapRunner (id)");
        $this->addSql("ALTER TABLE CapGoalSubscription ADD CONSTRAINT FK_D8F3EF63667D1AFE FOREIGN KEY (goal_id) REFERENCES CapGoal (id)");
        $this->addSql("DROP TABLE CapAchievement");
        $this->addSql("DROP TABLE capgoal_caprunner");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE CapAchievement (id INT AUTO_INCREMENT NOT NULL, runner_id INT DEFAULT NULL, goal_id INT DEFAULT NULL, date DATE NOT NULL, INDEX IDX_602468083C7FB593 (runner_id), INDEX IDX_60246808667D1AFE (goal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE capgoal_caprunner (capgoal_id INT NOT NULL, caprunner_id INT NOT NULL, INDEX IDX_C47E0FA0C50316F2 (capgoal_id), INDEX IDX_C47E0FA0997C15CA (caprunner_id), PRIMARY KEY(capgoal_id, caprunner_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE CapAchievement ADD CONSTRAINT FK_602468083C7FB593 FOREIGN KEY (runner_id) REFERENCES caprunner (id)");
        $this->addSql("ALTER TABLE CapAchievement ADD CONSTRAINT FK_60246808667D1AFE FOREIGN KEY (goal_id) REFERENCES capgoal (id)");
        $this->addSql("ALTER TABLE capgoal_caprunner ADD CONSTRAINT FK_C47E0FA0997C15CA FOREIGN KEY (caprunner_id) REFERENCES caprunner (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE capgoal_caprunner ADD CONSTRAINT FK_C47E0FA0C50316F2 FOREIGN KEY (capgoal_id) REFERENCES capgoal (id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE CapGoalSubscription");
    }
}
