<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121110150740 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE CapGoal ADD owner_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE CapGoal ADD CONSTRAINT FK_AF5F17A67E3C61F9 FOREIGN KEY (owner_id) REFERENCES CapRunner (id)");
        $this->addSql("CREATE INDEX IDX_AF5F17A67E3C61F9 ON CapGoal (owner_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE CapGoal DROP FOREIGN KEY FK_AF5F17A67E3C61F9");
        $this->addSql("DROP INDEX IDX_AF5F17A67E3C61F9 ON CapGoal");
        $this->addSql("ALTER TABLE CapGoal DROP owner_id");
    }
}
