<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121110210244 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE caprunner_capgoal");
        $this->addSql("ALTER TABLE capgoal CHANGE distance distance INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE caprunner_capgoal (caprunner_id INT NOT NULL, capgoal_id INT NOT NULL, INDEX IDX_2FDF1AAD997C15CA (caprunner_id), INDEX IDX_2FDF1AADC50316F2 (capgoal_id), PRIMARY KEY(caprunner_id, capgoal_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE caprunner_capgoal ADD CONSTRAINT FK_2FDF1AAD997C15CA FOREIGN KEY (caprunner_id) REFERENCES caprunner (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE caprunner_capgoal ADD CONSTRAINT FK_2FDF1AADC50316F2 FOREIGN KEY (capgoal_id) REFERENCES capgoal (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE CapGoal CHANGE distance distance INT DEFAULT NULL");
    }
}
