<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121109222144 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE CapGoal (id INT AUTO_INCREMENT NOT NULL, duration INT DEFAULT NULL, distance INT DEFAULT NULL, delay INT DEFAULT NULL, sum INT DEFAULT NULL, comment LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE capgoal_caprunner (capgoal_id INT NOT NULL, caprunner_id INT NOT NULL, INDEX IDX_C47E0FA0C50316F2 (capgoal_id), INDEX IDX_C47E0FA0997C15CA (caprunner_id), PRIMARY KEY(capgoal_id, caprunner_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE caprunner_capgoal (caprunner_id INT NOT NULL, capgoal_id INT NOT NULL, INDEX IDX_2FDF1AAD997C15CA (caprunner_id), INDEX IDX_2FDF1AADC50316F2 (capgoal_id), PRIMARY KEY(caprunner_id, capgoal_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE capgoal_caprunner ADD CONSTRAINT FK_C47E0FA0C50316F2 FOREIGN KEY (capgoal_id) REFERENCES CapGoal (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE capgoal_caprunner ADD CONSTRAINT FK_C47E0FA0997C15CA FOREIGN KEY (caprunner_id) REFERENCES CapRunner (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE caprunner_capgoal ADD CONSTRAINT FK_2FDF1AAD997C15CA FOREIGN KEY (caprunner_id) REFERENCES CapRunner (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE caprunner_capgoal ADD CONSTRAINT FK_2FDF1AADC50316F2 FOREIGN KEY (capgoal_id) REFERENCES CapGoal (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE capgoal_caprunner DROP FOREIGN KEY FK_C47E0FA0C50316F2");
        $this->addSql("ALTER TABLE caprunner_capgoal DROP FOREIGN KEY FK_2FDF1AADC50316F2");
        $this->addSql("DROP TABLE CapGoal");
        $this->addSql("DROP TABLE capgoal_caprunner");
        $this->addSql("DROP TABLE caprunner_capgoal");
    }
}
