<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121029140737 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE CapUser (id INT AUTO_INCREMENT NOT NULL, runner_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, lastname VARCHAR(100) DEFAULT NULL, firstname VARCHAR(100) DEFAULT NULL, UNIQUE INDEX UNIQ_DE102AC192FC23A8 (username_canonical), UNIQUE INDEX UNIQ_DE102AC1A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_DE102AC13C7FB593 (runner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE CapUser ADD CONSTRAINT FK_DE102AC13C7FB593 FOREIGN KEY (runner_id) REFERENCES CapRunner (id)");
        $this->addSql("DROP TABLE sfusers");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE sfusers (id INT AUTO_INCREMENT NOT NULL, runner_id INT DEFAULT NULL, username VARCHAR(25) NOT NULL, salt VARCHAR(32) NOT NULL, password VARCHAR(40) NOT NULL, email VARCHAR(60) NOT NULL, is_active TINYINT(1) NOT NULL, discr VARCHAR(255) NOT NULL, lastname VARCHAR(100) DEFAULT NULL, firstname VARCHAR(100) DEFAULT NULL, UNIQUE INDEX UNIQ_4CE0AB7BF85E0677 (username), UNIQUE INDEX UNIQ_4CE0AB7BE7927C74 (email), INDEX IDX_4CE0AB7B3C7FB593 (runner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE sfusers ADD CONSTRAINT FK_4CE0AB7B3C7FB593 FOREIGN KEY (runner_id) REFERENCES caprunner (id)");
        $this->addSql("DROP TABLE CapUser");
    }
}
